package com.voyage.ItenaryManagementService.service.serviceImpl;

import com.voyage.ItenaryManagementService.service.PredefinedItineraryActivityService;

public class PredefinedItineraryActivityServiceImpl implements PredefinedItineraryActivityService {
}
